# Generated by Django 4.2.7 on 2025-10-21 22:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tow_truck_app', '0002_supportticket_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Notification type',
                'verbose_name_plural': 'Notification types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Payment status',
                'verbose_name_plural': 'Payment statuses',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Ticket status',
                'verbose_name_plural': 'Ticket statuses',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'User type',
                'verbose_name_plural': 'User types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order status history', 'verbose_name_plural': 'Order status history'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='towtruck',
            options={'ordering': ['license_plate'], 'verbose_name': 'Tow truck', 'verbose_name_plural': 'Tow trucks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['name'], 'verbose_name': 'Tow truck type', 'verbose_name_plural': 'Tow truck types'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='towtruck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='towtruck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate per km'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tow_truck_app.order', verbose_name='Related order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type__code': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(verbose_name='Delivery latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(verbose_name='Delivery longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(verbose_name='Pickup address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_latitude',
            field=models.FloatField(verbose_name='Pickup latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_longitude',
            field=models.FloatField(verbose_name='Pickup longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Driver assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tow_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tow_truck_app.towtruck', verbose_name='Assigned tow truck'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tow_truck_app.vehicletype', verbose_name='Required tow truck type'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Driver assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=15, verbose_name='New status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Driver assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=15, verbose_name='Old status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tow_truck_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tow_truck_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='driver_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Driver rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tow_truck_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='service_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Service rating'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__code': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned operator'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='capacity',
            field=models.FloatField(verbose_name='Capacity (tons)'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='current_location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Current latitude'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='current_location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Current longitude'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__code': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last location update'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Plate'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='towtruck',
            name='vehicle_types',
            field=models.ManyToManyField(related_name='tow_trucks', to='tow_truck_app.vehicletype', verbose_name='Supported vehicle types'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tow_truck_user_set', related_query_name='tow_truck_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Phone verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='max_weight',
            field=models.FloatField(verbose_name='Max weight (tons)'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Vehicle ID')),
                ('nickname', models.CharField(blank=True, max_length=120, verbose_name='Nickname')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='License plate')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type__code': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Client vehicle',
                'verbose_name_plural': 'Client vehicles',
                'ordering': ['make', 'model', 'license_plate'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tow_truck_app.clientvehicle', verbose_name='Client vehicle'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(db_column='notification_type', on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='tow_truck_app.notificationtype', verbose_name='Notification type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tow_truck_app.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tow_truck_app.paymentstatus', verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tow_truck_app.ticketstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tow_truck_app.usertype', verbose_name='User type'),
        ),
    ]
